vector_db:
  index_name: "Markets"

retriever:
  top_k: 3
  score_threshold: 0.5

embedding_model:
  provider: "hugging-face"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

llm:
  google:
    provider: "google"
    model_name: "gemini-2.5-pro"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"

tools:
  tavily:
    max_results: 5